// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package moonpump

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Graduate is the `graduate` instruction.
type Graduate struct {
	Params *GrudateParams

	// [0] = [WRITE, SIGNER] operator
	//
	// [1] = [WRITE] bondingCurve
	//
	// [2] = [] config
	//
	// [3] = [WRITE] bondingCurveVault
	//
	// [4] = [] mint
	//
	// [5] = [] nativeMint
	//
	// [6] = [WRITE] admin
	//
	// [7] = [WRITE] creator
	//
	// [8] = [WRITE] bondingCurveTokenAccount
	//
	// [9] = [WRITE] operatorTokenAccount
	//
	// [10] = [WRITE] operatorNativeMintTokenAccount
	//
	// [11] = [] tokenProgram
	//
	// [12] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewGraduateInstructionBuilder creates a new `Graduate` instruction builder.
func NewGraduateInstructionBuilder() *Graduate {
	nd := &Graduate{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 13),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *Graduate) SetParams(params GrudateParams) *Graduate {
	inst.Params = &params
	return inst
}

// SetOperatorAccount sets the "operator" account.
func (inst *Graduate) SetOperatorAccount(operator ag_solanago.PublicKey) *Graduate {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(operator).WRITE().SIGNER()
	return inst
}

// GetOperatorAccount gets the "operator" account.
func (inst *Graduate) GetOperatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetBondingCurveAccount sets the "bondingCurve" account.
func (inst *Graduate) SetBondingCurveAccount(bondingCurve ag_solanago.PublicKey) *Graduate {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(bondingCurve).WRITE()
	return inst
}

// GetBondingCurveAccount gets the "bondingCurve" account.
func (inst *Graduate) GetBondingCurveAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetConfigAccount sets the "config" account.
func (inst *Graduate) SetConfigAccount(config ag_solanago.PublicKey) *Graduate {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(config)
	return inst
}

// GetConfigAccount gets the "config" account.
func (inst *Graduate) GetConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetBondingCurveVaultAccount sets the "bondingCurveVault" account.
func (inst *Graduate) SetBondingCurveVaultAccount(bondingCurveVault ag_solanago.PublicKey) *Graduate {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(bondingCurveVault).WRITE()
	return inst
}

// GetBondingCurveVaultAccount gets the "bondingCurveVault" account.
func (inst *Graduate) GetBondingCurveVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetMintAccount sets the "mint" account.
func (inst *Graduate) SetMintAccount(mint ag_solanago.PublicKey) *Graduate {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *Graduate) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetNativeMintAccount sets the "nativeMint" account.
func (inst *Graduate) SetNativeMintAccount(nativeMint ag_solanago.PublicKey) *Graduate {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(nativeMint)
	return inst
}

// GetNativeMintAccount gets the "nativeMint" account.
func (inst *Graduate) GetNativeMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetAdminAccount sets the "admin" account.
func (inst *Graduate) SetAdminAccount(admin ag_solanago.PublicKey) *Graduate {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(admin).WRITE()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *Graduate) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetCreatorAccount sets the "creator" account.
func (inst *Graduate) SetCreatorAccount(creator ag_solanago.PublicKey) *Graduate {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(creator).WRITE()
	return inst
}

// GetCreatorAccount gets the "creator" account.
func (inst *Graduate) GetCreatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetBondingCurveTokenAccountAccount sets the "bondingCurveTokenAccount" account.
func (inst *Graduate) SetBondingCurveTokenAccountAccount(bondingCurveTokenAccount ag_solanago.PublicKey) *Graduate {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(bondingCurveTokenAccount).WRITE()
	return inst
}

// GetBondingCurveTokenAccountAccount gets the "bondingCurveTokenAccount" account.
func (inst *Graduate) GetBondingCurveTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetOperatorTokenAccountAccount sets the "operatorTokenAccount" account.
func (inst *Graduate) SetOperatorTokenAccountAccount(operatorTokenAccount ag_solanago.PublicKey) *Graduate {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(operatorTokenAccount).WRITE()
	return inst
}

// GetOperatorTokenAccountAccount gets the "operatorTokenAccount" account.
func (inst *Graduate) GetOperatorTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetOperatorNativeMintTokenAccountAccount sets the "operatorNativeMintTokenAccount" account.
func (inst *Graduate) SetOperatorNativeMintTokenAccountAccount(operatorNativeMintTokenAccount ag_solanago.PublicKey) *Graduate {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(operatorNativeMintTokenAccount).WRITE()
	return inst
}

// GetOperatorNativeMintTokenAccountAccount gets the "operatorNativeMintTokenAccount" account.
func (inst *Graduate) GetOperatorNativeMintTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *Graduate) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *Graduate {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *Graduate) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *Graduate) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *Graduate {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *Graduate) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

func (inst Graduate) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Graduate,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Graduate) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Graduate) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Operator is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.BondingCurve is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Config is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.BondingCurveVault is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.NativeMint is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Admin is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.Creator is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.BondingCurveTokenAccount is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.OperatorTokenAccount is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.OperatorNativeMintTokenAccount is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *Graduate) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Graduate")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=13]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("               operator", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("           bondingCurve", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("                 config", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("      bondingCurveVault", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("                   mint", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("             nativeMint", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("                  admin", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("                creator", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("      bondingCurveToken", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("          operatorToken", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("operatorNativeMintToken", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("           tokenProgram", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("          systemProgram", inst.AccountMetaSlice.Get(12)))
					})
				})
		})
}

func (obj Graduate) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *Graduate) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewGraduateInstruction declares a new Graduate instruction with the provided parameters and accounts.
func NewGraduateInstruction(
	// Parameters:
	params GrudateParams,
	// Accounts:
	operator ag_solanago.PublicKey,
	bondingCurve ag_solanago.PublicKey,
	config ag_solanago.PublicKey,
	bondingCurveVault ag_solanago.PublicKey,
	mint ag_solanago.PublicKey,
	nativeMint ag_solanago.PublicKey,
	admin ag_solanago.PublicKey,
	creator ag_solanago.PublicKey,
	bondingCurveTokenAccount ag_solanago.PublicKey,
	operatorTokenAccount ag_solanago.PublicKey,
	operatorNativeMintTokenAccount ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *Graduate {
	return NewGraduateInstructionBuilder().
		SetParams(params).
		SetOperatorAccount(operator).
		SetBondingCurveAccount(bondingCurve).
		SetConfigAccount(config).
		SetBondingCurveVaultAccount(bondingCurveVault).
		SetMintAccount(mint).
		SetNativeMintAccount(nativeMint).
		SetAdminAccount(admin).
		SetCreatorAccount(creator).
		SetBondingCurveTokenAccountAccount(bondingCurveTokenAccount).
		SetOperatorTokenAccountAccount(operatorTokenAccount).
		SetOperatorNativeMintTokenAccountAccount(operatorNativeMintTokenAccount).
		SetTokenProgramAccount(tokenProgram).
		SetSystemProgramAccount(systemProgram)
}
