/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category AcceptOwnership
 * @category generated
 */
export const acceptOwnershipStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'AcceptOwnershipInstructionArgs'
)
/**
 * Accounts required by the _acceptOwnership_ instruction
 *
 * @property [_writable_, **signer**] pendingAdmin
 * @property [_writable_] config
 * @category Instructions
 * @category AcceptOwnership
 * @category generated
 */
export type AcceptOwnershipInstructionAccounts = {
  pendingAdmin: web3.PublicKey
  config: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const acceptOwnershipInstructionDiscriminator = [
  172, 23, 43, 13, 238, 213, 85, 150,
]

/**
 * Creates a _AcceptOwnership_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category AcceptOwnership
 * @category generated
 */
export function createAcceptOwnershipInstruction(
  accounts: AcceptOwnershipInstructionAccounts,
  programId = new web3.PublicKey('DrcCNopZABtZev6WkiBDsrwPfbJAcexx5jnVDZ7egLmS')
) {
  const [data] = acceptOwnershipStruct.serialize({
    instructionDiscriminator: acceptOwnershipInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.pendingAdmin,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.config,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
