/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import { BuyParams, buyParamsBeet } from '../types/BuyParams'

/**
 * @category Instructions
 * @category Buy
 * @category generated
 */
export type BuyInstructionArgs = {
  params: BuyParams
}
/**
 * @category Instructions
 * @category Buy
 * @category generated
 */
export const buyStruct = new beet.BeetArgsStruct<
  BuyInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['params', buyParamsBeet],
  ],
  'BuyInstructionArgs'
)
/**
 * Accounts required by the _buy_ instruction
 *
 * @property [_writable_, **signer**] buyer
 * @property [] config
 * @property [_writable_] bondingCurve
 * @property [] mint
 * @property [_writable_] bondingCurveTokenAccount
 * @property [_writable_] buyerTokenAccount
 * @property [_writable_] bondingCurveVault
 * @property [_writable_] feeRecipient
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category Buy
 * @category generated
 */
export type BuyInstructionAccounts = {
  buyer: web3.PublicKey
  config: web3.PublicKey
  bondingCurve: web3.PublicKey
  mint: web3.PublicKey
  bondingCurveTokenAccount: web3.PublicKey
  buyerTokenAccount: web3.PublicKey
  bondingCurveVault: web3.PublicKey
  feeRecipient: web3.PublicKey
  tokenProgram?: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const buyInstructionDiscriminator = [102, 6, 61, 18, 1, 218, 235, 234]

/**
 * Creates a _Buy_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category Buy
 * @category generated
 */
export function createBuyInstruction(
  accounts: BuyInstructionAccounts,
  args: BuyInstructionArgs,
  programId = new web3.PublicKey('DrcCNopZABtZev6WkiBDsrwPfbJAcexx5jnVDZ7egLmS')
) {
  const [data] = buyStruct.serialize({
    instructionDiscriminator: buyInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.buyer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.bondingCurve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.bondingCurveTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.buyerTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.bondingCurveVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.feeRecipient,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
