/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import { GrudateParams, grudateParamsBeet } from '../types/GrudateParams'

/**
 * @category Instructions
 * @category Graduate
 * @category generated
 */
export type GraduateInstructionArgs = {
  params: GrudateParams
}
/**
 * @category Instructions
 * @category Graduate
 * @category generated
 */
export const graduateStruct = new beet.BeetArgsStruct<
  GraduateInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['params', grudateParamsBeet],
  ],
  'GraduateInstructionArgs'
)
/**
 * Accounts required by the _graduate_ instruction
 *
 * @property [_writable_, **signer**] operator
 * @property [_writable_] bondingCurve
 * @property [] config
 * @property [_writable_] bondingCurveVault
 * @property [] mint
 * @property [] nativeMint
 * @property [_writable_] admin
 * @property [_writable_] creator
 * @property [_writable_] bondingCurveTokenAccount
 * @property [_writable_] operatorTokenAccount
 * @property [_writable_] operatorNativeMintTokenAccount
 * @category Instructions
 * @category Graduate
 * @category generated
 */
export type GraduateInstructionAccounts = {
  operator: web3.PublicKey
  bondingCurve: web3.PublicKey
  config: web3.PublicKey
  bondingCurveVault: web3.PublicKey
  mint: web3.PublicKey
  nativeMint: web3.PublicKey
  admin: web3.PublicKey
  creator: web3.PublicKey
  bondingCurveTokenAccount: web3.PublicKey
  operatorTokenAccount: web3.PublicKey
  operatorNativeMintTokenAccount: web3.PublicKey
  tokenProgram?: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const graduateInstructionDiscriminator = [
  45, 235, 225, 181, 17, 218, 64, 130,
]

/**
 * Creates a _Graduate_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category Graduate
 * @category generated
 */
export function createGraduateInstruction(
  accounts: GraduateInstructionAccounts,
  args: GraduateInstructionArgs,
  programId = new web3.PublicKey('DrcCNopZABtZev6WkiBDsrwPfbJAcexx5jnVDZ7egLmS')
) {
  const [data] = graduateStruct.serialize({
    instructionDiscriminator: graduateInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.operator,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.bondingCurve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.bondingCurveVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.nativeMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.admin,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.creator,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.bondingCurveTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.operatorTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.operatorNativeMintTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
