/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import { SellParams, sellParamsBeet } from '../types/SellParams'

/**
 * @category Instructions
 * @category Sell
 * @category generated
 */
export type SellInstructionArgs = {
  params: SellParams
}
/**
 * @category Instructions
 * @category Sell
 * @category generated
 */
export const sellStruct = new beet.BeetArgsStruct<
  SellInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['params', sellParamsBeet],
  ],
  'SellInstructionArgs'
)
/**
 * Accounts required by the _sell_ instruction
 *
 * @property [_writable_, **signer**] seller
 * @property [] config
 * @property [_writable_] bondingCurve
 * @property [_writable_] bondingCurveVault
 * @property [] mint
 * @property [_writable_] bondingCurveTokenAccount
 * @property [_writable_] sellerTokenAccount
 * @property [_writable_] feeRecipient
 * @category Instructions
 * @category Sell
 * @category generated
 */
export type SellInstructionAccounts = {
  seller: web3.PublicKey
  config: web3.PublicKey
  bondingCurve: web3.PublicKey
  bondingCurveVault: web3.PublicKey
  mint: web3.PublicKey
  bondingCurveTokenAccount: web3.PublicKey
  sellerTokenAccount: web3.PublicKey
  feeRecipient: web3.PublicKey
  tokenProgram?: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const sellInstructionDiscriminator = [
  51, 230, 133, 164, 1, 127, 131, 173,
]

/**
 * Creates a _Sell_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category Sell
 * @category generated
 */
export function createSellInstruction(
  accounts: SellInstructionAccounts,
  args: SellInstructionArgs,
  programId = new web3.PublicKey('DrcCNopZABtZev6WkiBDsrwPfbJAcexx5jnVDZ7egLmS')
) {
  const [data] = sellStruct.serialize({
    instructionDiscriminator: sellInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.seller,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.bondingCurve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.bondingCurveVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.bondingCurveTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.sellerTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.feeRecipient,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
