/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  UpdateConfigParams,
  updateConfigParamsBeet,
} from '../types/UpdateConfigParams'

/**
 * @category Instructions
 * @category UpdateConfig
 * @category generated
 */
export type UpdateConfigInstructionArgs = {
  params: UpdateConfigParams
}
/**
 * @category Instructions
 * @category UpdateConfig
 * @category generated
 */
export const updateConfigStruct = new beet.FixableBeetArgsStruct<
  UpdateConfigInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['params', updateConfigParamsBeet],
  ],
  'UpdateConfigInstructionArgs'
)
/**
 * Accounts required by the _updateConfig_ instruction
 *
 * @property [_writable_, **signer**] admin
 * @property [_writable_] config
 * @category Instructions
 * @category UpdateConfig
 * @category generated
 */
export type UpdateConfigInstructionAccounts = {
  admin: web3.PublicKey
  config: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const updateConfigInstructionDiscriminator = [
  29, 158, 252, 191, 10, 83, 219, 99,
]

/**
 * Creates a _UpdateConfig_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category UpdateConfig
 * @category generated
 */
export function createUpdateConfigInstruction(
  accounts: UpdateConfigInstructionAccounts,
  args: UpdateConfigInstructionArgs,
  programId = new web3.PublicKey('DrcCNopZABtZev6WkiBDsrwPfbJAcexx5jnVDZ7egLmS')
) {
  const [data] = updateConfigStruct.serialize({
    instructionDiscriminator: updateConfigInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.admin,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.config,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
