/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type GrudateParams = {
  nonce: number
  openTime: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const grudateParamsBeet = new beet.BeetArgsStruct<GrudateParams>(
  [
    ['nonce', beet.u8],
    ['openTime', beet.u64],
  ],
  'GrudateParams'
)
