/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  VanityPumpParams,
  vanityPumpParamsBeet,
} from '../types/VanityPumpParams'

/**
 * @category Instructions
 * @category VanityPump
 * @category generated
 */
export type VanityPumpInstructionArgs = {
  params: VanityPumpParams
}
/**
 * @category Instructions
 * @category VanityPump
 * @category generated
 */
export const vanityPumpStruct = new beet.FixableBeetArgsStruct<
  VanityPumpInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['params', vanityPumpParamsBeet],
  ],
  'VanityPumpInstructionArgs'
)
/**
 * Accounts required by the _vanityPump_ instruction
 *
 * @property [_writable_, **signer**] creator
 * @property [] config
 * @property [_writable_] mint
 * @property [_writable_] bondingCurve
 * @property [_writable_] bondingCurveVault
 * @property [_writable_] metadataAccount
 * @property [_writable_] bondingCurveTokenAccount
 * @property [_writable_] feeRecipient
 * @property [] tokenMetadataProgram
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category VanityPump
 * @category generated
 */
export type VanityPumpInstructionAccounts = {
  creator: web3.PublicKey
  config: web3.PublicKey
  mint: web3.PublicKey
  bondingCurve: web3.PublicKey
  bondingCurveVault: web3.PublicKey
  metadataAccount: web3.PublicKey
  bondingCurveTokenAccount: web3.PublicKey
  feeRecipient: web3.PublicKey
  tokenProgram?: web3.PublicKey
  tokenMetadataProgram: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  systemProgram?: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const vanityPumpInstructionDiscriminator = [
  161, 101, 23, 158, 187, 152, 157, 38,
]

/**
 * Creates a _VanityPump_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category VanityPump
 * @category generated
 */
export function createVanityPumpInstruction(
  accounts: VanityPumpInstructionAccounts,
  args: VanityPumpInstructionArgs,
  programId = new web3.PublicKey('DrcCNopZABtZev6WkiBDsrwPfbJAcexx5jnVDZ7egLmS')
) {
  const [data] = vanityPumpStruct.serialize({
    instructionDiscriminator: vanityPumpInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.creator,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.bondingCurve,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.bondingCurveVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.metadataAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.bondingCurveTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.feeRecipient,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenMetadataProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
