/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type SellParams = {
  amountIn: beet.bignum
  minimumAmountOut: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const sellParamsBeet = new beet.BeetArgsStruct<SellParams>(
  [
    ['amountIn', beet.u64],
    ['minimumAmountOut', beet.u64],
  ],
  'SellParams'
)
